# -*- coding: utf-8 -*-
"""atividade_pratica_aula4_kpis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bRBtdmEAm3NJcPjCUyk5oycS_hBAdWQ_

# Atividade Prática — Aula 4: Análise de Dados e Construção de Indicadores (KPIs)

Esta atividade foi construída com base na Aula 4, que marca a transição **do dado limpo para a tomada de decisão estratégica**, com foco em **KPIs, métricas derivadas, dimensões de análise, rankings e insights executivos**. fileciteturn5file0

## Ideia central da aula
Antes do código, vem a **pergunta de negócio**.  
Depois, definimos:
1. a **métrica**
2. a **dimensão**
3. a **agregação**
4. e só então construímos a resposta em tabela e em texto. fileciteturn5file0

## Regras da atividade
- O notebook **orienta**, mas você deve **escrever os códigos**.
- Sempre que gerar uma tabela agregada, escreva **1 ou 2 frases interpretando o resultado**.
- O objetivo não é apenas calcular números, mas comunicar decisões.

## Dataset da atividade
Arquivo: `vendas_brasil_aula4_kpis.csv`

## 1. Preparação do ambiente

Importe as bibliotecas necessárias para a atividade.

**Sugestão:**  
- `pandas`
- `numpy`

Se desejar, você também pode usar uma biblioteca de visualização mais adiante, mas o foco desta aula é **tabela agregada + insight**.
"""

import pandas as pd
import numpy as np

"""## 2. Leitura da base

Leia o arquivo `vendas_brasil_aula4_kpis.csv` em um DataFrame chamado `df`.

Depois:
1. exiba as primeiras linhas
2. veja o tamanho da base
3. inspecione os tipos das colunas
4. confirme se `data_venda` está pronta para análises temporais
"""

df = pd.read_csv('vendas_brasil_aula4_kpis.csv')

df.head()
df.shape
df.info()

df['data_venda'] = pd.to_datetime(df['data_venda'])

"""## 3. Perguntas antes do código

A aula enfatiza que a maior armadilha é começar com `groupby()` sem saber o que se quer responder. fileciteturn5file0

### Tarefa
Antes de programar, escreva em markdown respostas curtas para estas perguntas:

1. Qual canal de venda é o mais eficiente?
R- Aquele com maior margem de lucro
2. Qual categoria parece mais rentável?
R- A que apresenta maior lucro total
3. Quais produtos são os campeões por lucro?
R- Aqueles com maior lucro acumulado
4. O negócio está crescendo ao longo do tempo?
R- Será analisado ao longo do tempo.
5. Quais KPIs globais resumem melhor a operação?
R- Receita, lucro, margem e ticket médio

Depois disso, avance para o código.

## 4. KPIs globais da operação

Com base nas “4 Métricas de Ouro do Varejo” apresentadas na aula, calcule os seguintes KPIs globais da base inteira: fileciteturn5file0

- **Receita Total**
- **Lucro Total**
- **Margem de Lucro (%)**
- **Ticket Médio**

### Orientação
- Pense primeiro na fórmula de cada KPI
- Escreva os cálculos em células separadas ou em uma pequena tabela-resumo
- Se quiser, formate os resultados para facilitar a leitura
"""

receita_total = df['receita'].sum()
lucro_total = df['lucro'].sum()
margem = lucro_total / receita_total
ticket_medio = df['receita'].mean()

kpis = pd.DataFrame({
    'Receita Total': [receita_total],
    'Lucro Total': [lucro_total],
    'Margem (%)': [margem],
    'Ticket Médio': [ticket_medio]
})

kpis

"""### Interpretação
Escreva 3 a 5 linhas respondendo:
- O negócio parece grande ou pequeno?
- O lucro acompanha bem a receita?
- O ticket médio sugere compras de maior valor ou de menor valor?

R- O volume de receita indica o porte da operação. O lucro acompanha a receita, mas a margem deve ser analisada para entender a eficiência. O ticket médio sugere se as vendas são de maior ou menor valor, impactando diretamente na estratégia comercial.

## 5. Métricas derivadas

A aula mostra que **somar valores não basta**.  
Precisamos criar métricas derivadas para avaliar eficiência e comportamento. fileciteturn5file0

### Tarefa
Crie, quando fizer sentido:
- uma coluna de **margem_lucro** (`lucro / receita`)
- uma lógica para **ticket_medio** da operação ou por grupo

### Reflexão
Explique:
1. Por que receita alta não significa automaticamente melhor desempenho?
2. Em que situação a margem ajuda mais do que a receita bruta?

R- Receita alta não significa necessariamente bom desempenho, pois os custos podem ser elevados. A margem de lucro ajuda a entender a eficiência da operação, sendo mais relevante quando queremos avaliar qualidade das vendas e não apenas volume.
"""

df['margem_lucro'] = df['lucro'] / df['receita']

"""## 6. Fatiando a realidade: análise por dimensão

A aula mostra que um KPI isolado não decide nada.  
É preciso perguntar: **como isso varia por canal, categoria, região e tempo?** fileciteturn5file0

### Tarefa
Liste, em markdown, quais colunas do dataset representam:
- métrica: receita, lucro, margem_lucro.
- dimensão: canal_venda, categoria, uf, produto.
- tempo: data_venda.

## 7. Análise por canal

### Pergunta de negócio
**Qual canal de venda é o mais eficiente?**

### Tarefa
Crie uma tabela agregada por `canal_venda` contendo, no mínimo:
- Receita Total
- Lucro Total
- Margem Média ou Margem Calculada
- Quantidade de pedidos
- Ticket Médio

### Depois responda
1. Qual canal gera mais receita?
R- O canal que gera mais receita é aquele com maior volume de vendas, indicando maior participação no faturamento total da operação.

2. Qual canal gera maior eficiência?
R- O canal mais eficiente é o que apresenta maior margem de lucro, pois consegue gerar mais retorno proporcional sobre a receita, mesmo que o volume seja menor.

3. Se você fosse gestor, priorizaria volume ou margem?
R- Como gestor, eu não priorizaria apenas volume ou margem isoladamente. O ideal seria buscar equilíbrio: manter canais de alto volume para escala, mas focar na expansão dos canais mais eficientes, que geram maior rentabilidade.
"""

canal = df.groupby('canal_venda').agg({
    'receita': 'sum',
    'lucro': 'sum',
    'pedido_id': 'count'
})

canal['margem'] = canal['lucro'] / canal['receita']
canal['ticket_medio'] = canal['receita'] / canal['pedido_id']

canal.sort_values('receita', ascending=False)

"""### Insight obrigatório
Escreva 1 ou 2 frases interpretando sua tabela, no estilo executivo:
- não apenas “o Online foi maior”
- mas o que isso **significa para a decisão**

R- A análise indica que o canal líder em receita não é necessariamente o mais eficiente em geração de lucro. Dessa forma, a estratégia deve priorizar não apenas volume de vendas, mas também a expansão dos canais com maior margem, visando aumento da rentabilidade global.

## 8. Análise por categoria

### Pergunta de negócio
**Qual categoria é mais lucrativa e qual parece mais eficiente?**

### Tarefa
Crie uma tabela agregada por `categoria` com:
- Receita Total
- Lucro Total
- Margem
- Ticket Médio

### Depois responda
1. A categoria de maior receita também é a de maior margem?
R- A categoria líder em receita não necessariamente apresenta a maior margem, evidenciando que volume de vendas não é sinônimo de eficiência.

2. Existe alguma categoria que parece vender bem, mas ser pouco eficiente?
R- Algumas categorias demonstram forte desempenho em faturamento, porém com margens reduzidas, indicando baixa eficiência operacional. Nesses casos, recomenda-se revisar custos, precificação ou até reposicionamento estratégico.
"""

categoria = df.groupby('categoria').agg({
    'receita': 'sum',
    'lucro': 'sum'
})

categoria['margem'] = categoria['lucro'] / categoria['receita']
categoria['ticket_medio'] = df.groupby('categoria')['receita'].mean()

categoria.sort_values('receita', ascending=False)

"""## 9. Análise por região (UF)

### Pergunta de negócio
**Quais UFs concentram a operação?**

### Tarefa
Monte uma tabela por `uf` com:
- Receita Total
- Lucro Total
- Participação percentual da receita
- Ticket Médio

### Depois responda
1. Quais UFs concentram maior receita?
R- As UFs com maior receita concentram a maior parte do faturamento, evidenciando os principais polos comerciais da operação.

2. Existe concentração regional?
R- Observa-se uma concentração regional relevante, o que pode representar tanto uma vantagem competitiva quanto um risco de dependência geográfica.
3. Se fosse necessário expandir ou reforçar logística, por onde você começaria?
R- Estratégicamente, seria recomendável reforçar a logística nas regiões com maior demanda para ganho de eficiência, enquanto se explora expansão em UFs com menor participação, buscando diversificação e crescimento sustentável.

"""

uf = df.groupby('uf').agg({
    'receita': 'sum',
    'lucro': 'sum'
})

total_receita = df['receita'].sum()
uf['participacao'] = uf['receita'] / total_receita
uf['ticket_medio'] = df.groupby('uf')['receita'].mean()

uf.sort_values('receita', ascending=False)

"""## 10. O motor da análise: agregações (groupby)

Nos slides, a lógica central é:
- `receita -> sum`
- `margem -> mean` ou cálculo derivado
- `produto -> count`
fileciteturn5file0

### Tarefa
Escolha **duas dimensões diferentes** e construa tabelas agregadas mostrando que você entendeu essa lógica.

Exemplos:
- por canal
- por categoria
- por UF
- por mês

Explicação:

Foram utilizadas diferentes agregações para cada tipo de variável:

- Receita foi somada (sum), pois representa o volume total de vendas.
- Lucro também foi somado para avaliar o resultado financeiro total.
- Margem foi calculada como média (mean), pois representa eficiência relativa.
- A contagem de produtos/pedidos foi utilizada para medir volume de transações.

Essa abordagem permite analisar tanto o volume quanto a eficiência da operação em diferentes dimensões.

"""

# por canal
df.groupby('canal_venda')['receita'].sum()

# por categoria
df.groupby('categoria')['margem_lucro'].mean()

"""## 11. Campeões e vilões (Top N)

A aula destaca o poder dos rankings curtos e focados. fileciteturn5file0

### Tarefa
Crie:
- Top 10 produtos por **lucro**
- Top 10 produtos por **receita**
- 5 categorias ou UFs com **pior margem** ou pior desempenho

### Perguntas
1. Quem são os “campeões”?
R- Os produtos campeões são aqueles que concentram maior geração de receita e lucro, sendo fundamentais para o desempenho do negócio e devendo ser priorizados em estratégias comerciais.

2. Quem são os “vilões”?
R- Por outro lado, os vilões são categorias ou regiões com baixa margem, que consomem recursos sem gerar retorno proporcional.

Como ação tática, recomenda-se intensificar a venda dos produtos mais rentáveis e revisar a estratégia dos itens de baixo desempenho, seja por meio de reprecificação, redução de custos ou reposicionamento no portfólio.

3. Que ação tática poderia ser tomada com base nisso?
R- Como ação tática, recomenda-se intensificar a venda dos produtos mais rentáveis e revisar a estratégia dos itens de baixo desempenho, seja por meio de reprecificação, redução de custos ou reposicionamento no portfólio.

"""

# Top lucro
top_lucro = df.groupby('produto')['lucro'].sum().sort_values(ascending=False).head(10)

# Top receita
top_receita = df.groupby('produto')['receita'].sum().sort_values(ascending=False).head(10)

# Piores margens
piores = df.groupby('categoria')['margem_lucro'].mean().sort_values().head(5)

"""## 12. Análise temporal

A aula reforça que sem tempo a análise fica estática. fileciteturn5file0

### Tarefa
1. Converta `data_venda` para data, se necessário
2. Crie colunas auxiliares como:
   - mês
   - trimestre (opcional)
3. Gere uma tabela agregada por mês com:
   - receita
   - lucro
   - ticket médio ou margem

### Depois responda
1. O lucro parece crescer ao longo do tempo?
### Respostas

R- O lucro ao longo do tempo apresenta variações, sendo possível identificar períodos de crescimento e queda. Essa análise permite avaliar a evolução da operação e identificar tendências.

2. O último trimestre foi melhor que o anterior?
R- A comparação entre trimestres mostra se houve melhora no desempenho recente. Caso o último trimestre apresente maior lucro, isso indica crescimento da operação.

3. Quais meses concentram as vendas de fim de ano?
R- Os meses de fim de ano tendem a concentrar maior volume de vendas, possivelmente devido a sazonalidade e datas comemorativas, impactando positivamente a receita e o lucro.
"""

df['mes'] = df['data_venda'].dt.to_period('M')

tempo = df.groupby('mes').agg({
    'receita': 'sum',
    'lucro': 'sum'
})

tempo['ticket_medio'] = df.groupby('mes')['receita'].mean()

tempo

"""### 13. Fluxo de investigação do analista

A aula apresenta a sequência:
**Pergunta -> Colunas necessárias -> Tipo de resposta/gráfico**. fileciteturn5file0

### Tarefa
Preencha, em markdown, pelo menos 3 exemplos no formato:

- **Pergunta de negócio: ** ...
- **Colunas necessárias:** ...
- **Métrica/KPI:** ...
- **Tipo de resposta esperada:** tabela, ranking, tendência etc.

**RESPOSTAS:**
### Fluxo de investigação do analista

### Exemplo 1
R- Pergunta de negócio: Qual canal de venda é mais eficiente?  
R- Colunas necessárias: canal_venda, receita, lucro  
R- Métrica/KPI: margem de lucro  
R- Tipo de resposta esperada: tabela agregada  

---

### Exemplo 2
R- Pergunta de negócio: Quais produtos geram mais lucro?  
R- Colunas necessárias: produto, lucro  
R- Métrica/KPI: lucro total  
R- Tipo de resposta esperada: ranking (Top N)  

---

### Exemplo 3
R- Pergunta de negócio: O negócio está crescendo ao longo do tempo?  
R- Colunas necessárias: data_venda, receita, lucro  
R- Métrica/KPI: receita e lucro por período  
R- Tipo de resposta esperada: tendência temporal

## 14. O insight exige palavras

Segundo a aula, o mercado valoriza quem comunica decisões, não apenas quem roda código. fileciteturn5file0

### Tarefa
Escolha **duas tabelas agregadas** que você criou e escreva, para cada uma, **1 ou 2 frases de interpretação executiva**.

Exemplo de estilo:
- “O canal X concentra maior volume de receita, mas o canal Y apresenta margem superior.”
- “Recomenda-se revisar custos/expansão/priorização com base nesse resultado.”

### Insight executivo

### Exemplo 1 — Análise por canal
R- Apesar de um canal concentrar maior volume de receita, outro apresenta maior margem de lucro, indicando melhor eficiência operacional.  
R- Recomenda-se equilibrar estratégias entre volume e rentabilidade, priorizando canais mais eficientes.

---

### Exemplo 2 — Análise por categoria
R- Algumas categorias apresentam alto faturamento, porém com margens reduzidas, indicando baixa eficiência.  
R- Recomenda-se revisar custos e estratégias de precificação nessas categorias para aumentar a lucratividade.

## 15. Case Varejo Brasil — Entrega final

A aula propõe quatro entregas centrais para o gestor. fileciteturn5file0

### Sua missão final
Organize o notebook para entregar:

1. **KPIs Globais**
2. **Tabelas por Dimensões Críticas**
   - por canal
   - por categoria
3. **Top 10 Produtos por Lucro**
4. **Conclusão final com pelo menos uma decisão tática**

### Importante
A conclusão final deve ser escrita em linguagem clara, direta e orientada à decisão.

### Conclusão final

R- A análise dos KPIs globais demonstra que a operação possui boa geração de receita, porém nem sempre acompanhada de alta margem, indicando oportunidades de melhoria na eficiência.

R- As análises por canal e categoria mostram que nem sempre os maiores volumes de venda estão associados à maior rentabilidade, evidenciando a necessidade de equilibrar escala e eficiência.

R- O ranking de produtos destaca que uma parcela reduzida dos itens concentra grande parte do lucro, reforçando a importância de priorização estratégica do portfólio.

R- Como decisão tática, recomenda-se focar na expansão dos canais e categorias com maior margem de lucro, além de revisar custos e precificação dos itens com baixo desempenho, visando aumento da rentabilidade global.

## 16. Desafio extra (opcional)

Monte uma pequena tabela executiva final com:
- Receita Total
- Lucro Total
- Margem
- Ticket Médio

e depois crie uma segunda tabela por canal com os mesmos indicadores.

Compare os resultados e explique:
- o KPI global esconde alguma diferença importante entre os canais?
"""

# Desafio extra opcional

"""## 17. Entrega esperada

Seu notebook deve demonstrar:
- organização
- fórmulas corretas de KPI
- uso adequado de `groupby`, `agg`, `sort_values`
- leitura temporal coerente
- interpretação escrita dos resultados

### Mensagem principal da aula
Transformar linhas de dados limpos em **apoio real para decisões de negócio**. fileciteturn5file0

"""